version: "2"
services:
  mqtt:
    image: eclipse-mosquitto

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
  
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
      - /dev/snd:/dev/snd
    links:
      - mqtt
      - influxdb
